### ISSUE TITLE
API usage

### ISSUE THREAD

**Issue by ahowell1** [jfrisella/WistiaAPI#1]
I notice that there are a lot of classes in the project. I wanted to implement this into a Wordpress plugin to make a quick update to multiple Medias in a Wistia Project but was unsure if there was a main file that connected all of the needed classes? Is everything needed for tests already connected in the Wistia.php file?

**Comment by jfrisella** [comment]
Yeah, sorry for all the folders.  I was using it as a learning tool for composer.  If you use composer, then you should be able to get it [HERE](https://packagist.org/packages/jafrisella/wistia_api).  If not, I quickly created an include file [HERE](https://github.com/jfrisella/WistiaAPI/blob/master/include/include.php).  That should include all the needed files.  Do be warned though, I have never actually tested this AT ALL.  Please let me know if you run into any problems.  I will gladly try to make changes.

**Comment by jfrisella** [comment]
And I made a few changes to the project after you contacted me.  Just in case you already downloaded the src, you may need to do it again.
